kafka:
  bootstrap:
    servers: kafka:9094
  topic: gps
  group: gps-consumer

log:
  level: debug # debug, info, warn, error, fatal, panic
  format: text # or json

postgres:
  host: "postgres"
  port: "5432"
  user: tracker
  password: tracker
  database: tracker
  table: position
  sslmode: disable
